If you are upgrading from a previous version of the plugin to the {version}, you will need to take into account the following changes.

==== Configuration Changes

The version 4 of the Neo4j driver contains changes in the configuration builder which require configuration changes to conform to them. For example `grails.neo4j.options.maxSessions` is now `grails.neo4j.options.maxConnectionPoolSize`. Some configuration defaults have also changed, so be sure to check the documentation of the driver for more information.

==== Bolt Java Driver and API Changes

The API has changed to accommodate the new Neo4j Bolt driver.

Therefore you need to replace the usages of the following interfaces with their bolt equivalents:

[format="csv", options="header"]
|===

Class, Replacement
org.neo4j.driver.v1.Driver, org.neo4j.driver.Driver
org.neo4j.driver.v1.Transaction, org.neo4j.driver.Transaction
org.neo4j.driver.v1.types.Node, org.neo4j.driver.types.Node
org.neo4j.driver.v1.types.Relationship, org.neo4j.driver.types.Relationship
org.neo4j.driver.v1.StatementResult, org.neo4j.driver.Result
|===

There may be other classes that you need to replace references too. The `org.neo4j.driver.v1` package has shed its `v1` package, however there are also other changes.
