The following options can be configured in `grails-app/conf/application.yml`:

* `grails.neo4j.url` - The Neo4j Bolt URL
* `grails.neo4j.buildIndex` - Whether to build the Neo4j index on startup (defaults to true)
* `grails.neo4j.type` - The Neo4j server type. If set to `embedded` loads an embedded server
* `grails.neo4j.flush.mode` - The flush mode to use when working with Neo4j sessions. Default to `AUTO`.
* `grails.neo4j.username` - The username to use to authenticate
* `grails.neo4j.password` - The password to use to authenticate
* `grails.neo4j.default.mapping` - The default database mapping. Must be a closure configured in `application.groovy`
* `grails.neo4j.options` - Any options to be passed to the driver

The `grails.neo4j.options` setting allows you to configure the properties of http://neo4j.com/docs/api/java-driver/1.0/org/neo4j/driver/v1/Config.html[org.neo4j.driver.v1.Config], for example:


[source,yaml]
----
grails:
    neo4j:
        options:
            maxSessions: 100
            encryptionLevel: NONE
            sessionLivenessCheckTimeout: 200
----
